services:
  project_zomboid_server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "project_zomboid_server"
    volumes:
      - ./config/Zomboid:/home/zomboid/Zomboid:rw
      - ./config/Steam:/home/zomboid/Steam:rw
      - ./server_files:/app/pz-server:rw
    ports:
      - "16261:16261" # Main server port
      - "8766:8766"   # Steam query port
      - "27015:27015" # RCON
      - "16262:16262"
    environment:
      - PZ_SERVER_NAME=LaZone
      - PZ_ADMIN_PASSWORD=rdd9bQX8JfJ
    restart: always
